# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=20)),
                ('street2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Church_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptized_date', models.DateTimeField()),
                ('baptized_church', models.CharField(max_length=15)),
                ('aquaintance', models.CharField(max_length=30)),
                ('service_experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=15)),
                ('residential_phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'duties',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_relationship', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Person_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('job', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=15)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person'),
        ),
        migrations.AddField(
            model_name='duty',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person'),
        ),
        migrations.AddField(
            model_name='church_info',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchForm.Person'),
        ),
    ]
