# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchForm', '0003_person_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='middle_name',
            new_name='second_name',
        ),
    ]
