# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchForm', '0004_auto_20180324_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
