# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchForm', '0005_auto_20180324_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='second_name',
        ),
    ]
